[project]
name = "ickas-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pypdf>=6.7.3",
    "python-docx>=1.2.0",
]
